name: shimmie-board
services:
- name: web
  github:
    repo: your-username/your-repo
    branch: main
  envs:
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_NAME
    value: ${db.DATABASE}
  - key: DB_USER
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
databases:
- engine: MYSQL
  name: shimmie-db
  version: "8" 