name: shimmie-board
services:
- name: web
  github:
    repo: your-username/your-repo
    branch: main
  envs:
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_NAME
    value: ${db.DATABASE}
  - key: DB_USER
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: "https://shxpeyjwjjlbqfoclqgu.supabase.co"
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeHBleWp3ampsYnFmb2NscWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NTEyMTEsImV4cCI6MjA1NDUyNzIxMX0.EkwYjvsaiuCVaFt_2b9_cqnrDBrN2w0_2vI9UAVEQd4"
databases:
- engine: MYSQL
  name: shimmie-db
  version: "8" 